name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main  # Passe das ggf. an deinen Hauptbranch an

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Root-Verzeichnis enthält HTML/CSS/JS
